# Generated by Django 2.1.5 on 2019-02-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190212_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='created_date',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='photo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='vbncvbn', max_length=200),
        ),
    ]
