# Generated by Django 2.1.5 on 2019-02-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190213_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photos',
            new_name='Photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
    ]
