# Generated by Django 2.1.5 on 2019-02-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190213_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.AlterField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
    ]
