# Generated by Django 2.1.5 on 2019-02-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190215_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
    ]
